version: "3.4"

services:

  # ============================================================================
  # frontend
  # ============================================================================
  app:
    build:
      context: .
      target: base
    ports:
      - 8080:8080
      - 9230:9230
    volumes:
      # configurations
      - REACT_APP_API_BASE=http://localhost:8081

      # application
      - ./public:/opt/cla/public
      - ./src/assets:/opt/cla/src/assets
      - ./src/components:/opt/cla/src/components
      - ./src/views:/opt/cla/src/views
      - ./src/utilities:/opt/cla/src/utilities
      - ./src/App.js:/opt/cla/src/App.js
      - ./src/index.js:/opt/cla/src/index.js
      - ./src/index.css:/opt/cla/src/index.css
      - ./src/App.css:/opt/cla/src/App.css

      # configuration
      - ./config/.browserslistrc:/opt/cla/.browserslistrc
      - ./config/craco.config.js:/opt/cla/craco.config.js
      - ./config/default.eslintrc.json:/opt/cla/default.eslintrc.json

      # testing
      - ./test:/opt/cla/src/__tests__
  # ============================================================================
  # persistence
  # ============================================================================
  # sql:
  #   image: todo-web-api_sql:latest
  #   ports:
  #     - 1433:1433
  #   environment:
  #     # configuration
  #     - SA_PASSWORD=Abcde12345
  #     - INIT_DB_NAME=api
  #   volumes:
  #     - mssql:/var/opt/mssql

  ### ==========================================================================
  ### backend
  ### ==========================================================================
  # api:
  #   image: todo-web-api_app:latest
  #   command: >
  #     sh -c './wait-for.sh -t 300 sql:1433 \
  #      -- npm run start'
  #   ports:
  #     - 8081:8080
  #   environment:
  #     # logging
  #     - LOG_LEVEL=debug

  #     # database
  #     - DB_SQL_HOST=sql
  #     - DB_SQL_PORT=1433
  #     - DB_SQL_USERNAME=sa
  #     - DB_SQL_PASSWORD=Abcde12345
  #     - DB_SQL_DATABASE=api

  #     # fix for WSL2 file watch limitation
  #     - CHOKIDAR_USEPOLLING=true
  #   healthcheck:
  #     disable: true
  #   depends_on:
  #     - sql

volumes:
  mssql:
