version: "3.4"

services:

  # ============================================================================
  # frontend
  # ============================================================================
  app:
    build:
      context: .
      target: base
    ports:
      - 8080:8080
      - 9230:9230
    volumes:
      # application
      - ./public:/opt/cla/public
      - ./src/assets:/opt/cla/src/assets
      - ./src/components:/opt/cla/src/components
      - ./src/views:/opt/cla/src/views
      - ./src/utilities:/opt/cla/src/utilities
      - ./src/App.js:/opt/cla/src/App.js
      - ./src/index.js:/opt/cla/src/index.js
      - ./src/index.css:/opt/cla/src/index.css
      - ./src/App.css:/opt/cla/src/App.css

      # configuration
      - ./config/.browserslistrc:/opt/cla/.browserslistrc
      - ./config/craco.config.js:/opt/cla/craco.config.js
      - ./config/default.eslintrc.json:/opt/cla/default.eslintrc.json

      # testing
      - ./test:/opt/cla/src/__tests__
