@id=1

### Create todo
POST {{host}}/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvaWQiOiIwMDAwMDAwMC0wMDAwLTAwMDAtMDAwMC0wMDAwMDAwMDAwMDAiLCJzY3AiOiJUb2Rvcy5SZWFkIiwicm9sZXMiOlsiQWRtaW5pc3RyYXRvciJdLCJhenAiOiJhMDdlMDNmMy0yNDY2LTRlOGYtOWRiZC0xYzRkYzdhMjljYmIiLCJuYW1lIjoiQ0xBLCBEZXZlbG9wZXIiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJjbGEuZGV2ZWxvcGVyQGludmFsaWQuY29tIn0.pkQ1jIP-kIcYddrRmJAtxS4_wir3JkYofvl-lNCT_iI
Content-Type: application/json

{
  "email": "zak.edwards@claconnect.com",
  "userName": "zedwards",
  "firstName": "Zak",
  "lastName": "Edwards"
}